resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: my-file
  type: file-url
  source:
    url: https://raw.githubusercontent.com/pivotalservices/concourse-curl-resource/master/test/data/pivotal-1.0.0.txt
    filename: pivotal-1.0.0.txt

jobs:
- name: run-and-get-file
  plan:
  - get: my-file
  - task: run-and-get-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      inputs:
      - name: my-file
      run:
        path: sh
        args:
        - -exc
        - |
          find .
