resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: my-file-with-last-modified-info
  type: file-url
  source:
    url: https://s3-us-west-1.amazonaws.com/lsilva-bpws/PCF_usage/pcf-sandbox-usage-from-2016-09-01-to-2016-09-30_1475771124.json
    filename: pcf-sandbox-usage.json
- name: my-file-without-last-modified-info
  type: file-url
  source:
    url: https://raw.githubusercontent.com/pivotalservices/concourse-curl-resource/master/test/data/pivotal-1.0.0.txt
    filename: pivotal-1.0.0.txt
- name: my-file-requiring-auth
  type: file-url
  source:
    url: https://auth-demo.aerobatic.io/protected-standard
    filename: auth-request-response.txt
    username: aerobatic
    password: aerobatic

jobs:
- name: run-and-get-files
  plan:
  - get: my-file-with-last-modified-info
  - get: my-file-without-last-modified-info
  - get: my-file-requiring-auth
  - task: run-and-get-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      inputs:
      - name: my-file-with-last-modified-info
      - name: my-file-without-last-modified-info
      - name: my-file-requiring-auth
      run:
        path: sh
        args:
        - -exc
        - |
          find .
          cat ./my-file-requiring-auth/auth-request-response.txt | grep expecting
