resource_types:
- name: curl
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: single-file
  type: curl
  source:
    url: https://s3-us-west-1.amazonaws.com/lsilva-bpws/PCF_usage/pcf-sandbox-usage-from-2016-09-01-to-2016-09-30_1475771124.json
    filename: pcf-sandbox.json

jobs:
- name: run-and-get-file
  plan:
  - get: single-file
  - task: run-and-get-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: "latest"
      inputs:
      - name: single-file
      run:
        path: sh
        args:
        - -exc
        - |
          find .
