#!/usr/bin/env ash

set -o errexit -o nounset -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source "$(dirname $0)/common.sh"

tmpd="$(mktemp -d /tmp/concourse-curl-resource-request.XXXXXX)"
payload="$tmpd/payload"

cat > "$payload" <&0

url="$(jq -r '.source.url // ""' < $payload)"
extra_args="$(jq -r '.source.extra_args // ""' < $payload)"

if test -z "$url"; then
  echo "invalid payload (missing url)"
  exit 1
fi

check_version "$tmpd" "$url" "$extra_args" >&3
