name: ci

on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-push-pr
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/3dhubs/concourse-curl-resource:pr${{ github.event.number }}
      - name: build-push-master
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/3dhubs/concourse-curl-resource:master
